site: Milo's Projects and Ramblings
url: http://more.milofultz.com/
title: Milo's Projects and Ramblings
description: This is my repo for all my weird ideas and projects
twitter:
  username: milofultzbass
  card: summary
  creator: milofultzbass
author:
  twitter: milofultzbass
  name: Milo Fultz
  avatar:
  email: milopfultz@gmail.com
  url: http://more.milofultz.com/
permalink: pretty

baseurl: ""

highlighter: none

exclude:
  - .jekyll-cache
  
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
  sass_dir: _sass
  style: :compressed

plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap  
  - jekyll-target-blank

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:year/:month/:day/:slug
  
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"